services:
  - type: web
    name: whatsapp-status-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: PORT
        value: 3000
